version: '3.10'

volumes:
  te_data:

networks:
  te_network:
  
services:
  frontend:
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always
    build:
      context: ./te-frontend/
      dockerfile: Dockerfile
    networks:
      - te_network

  backend:
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    build:
      context: ./te-backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - te_network

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - te_data:/var/lib/postgresql/data

  



