version: '3.10'

services:
  backend:
    container_name: te_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    build:
      context: ./te-backend
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - te_network
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}

  frontend:
    container_name: te_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always
    build:
      context: ./te-frontend/
      dockerfile: Dockerfile
    networks:
      - te_network
    command: npm start

  db:
    container_name: te_db
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - te_volume:/var/lib/postgresql/data
    networks:
      - te_network

volumes:
  te_volume:

networks:
  te_network:
