version: '3.10'

volumes:
  db_data:
  alembic_data:

networks:
  te_network:
  
services:
  frontend:
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    restart: always
    build:
      context: ./te-frontend
      dockerfile: Dockerfile
    command: npm start
    networks:
      - te_network

  backend:
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    restart: always
    build:
      context: ./te-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./te-backend/alembic:/app/alembic  # Mount Alembic directory
      - alembic_data:/app/alembic  # Mount Alembic data directory
    networks:
      - te_network
    

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${POSTGRES_HOST}", "-p", "${POSTGRES_PORT}", "-q", "-U", "${POSTGRES_USER}"]
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - te_network
    
